[package]
name = "nlx-gateway"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.65"
clap = { version = "4.0.17", features = ["derive", "env"] }
hostname = "0.3.1"
log = "0.4.17"
pretty_env_logger = "0.4.0"
prost = "0.11.0"
tokio = { version = "1.21.2", features = ["full"] }
tonic = { version = "0.8.2", features = ["tls"] }
serde = { version = "1.0.145", features = ["derive"] }
rocket = { version = "0.5.0-rc.2", features = ["json", "mtls"]}

[build-dependencies]
#prost-build = { version = "0.11.1" }
tonic-build = "0.8.2"
