[package]
name = "nlx-gateway"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = { version = "0.14.20", features = ["full"] }
log = "0.4.17"
pretty_env_logger = "0.4.0"
tokio = { version = "1.21.2", features = ["full"] }
